$$\textbf{Exponential population growth }$$

$$\frac{dy}{dt} = ky$$

In [24]:
import numpy as np 
import matplotlib.pyplot as plt

k= 0.5
N_O= 10

t=np.arange(0,10)
N = np.arange(0, 100, 10)

T, N_grid = np.meshgrid(t,N)


dN = k * N_grid
dt = 1 

plt.figure(figsize=(8,6))

plt.quiver(T, N_grid, dt, dN, angles='xy', scale_units='xy', scale=5, color='blue')

# Optional: plot the analytical solution
N_sol = N_O * np.exp(k * t)
plt.plot(t, N_sol, 'r', label='N(t) = N0*exp(k*t)')

plt.xlabel("Time t")
plt.ylabel("Population N")
plt.title("Slope Field with Exponential Growth Solution")
plt.grid(True)
plt.legend()
plt.show()

[0 1 2 3 4 5 6 7 8 9]
[ 0 10 20 30 40 50 60 70 80 90]
[[0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]
 [0 1 2 3 4 5 6 7 8 9]]
[[ 0  0  0  0  0  0  0  0  0  0]
 [10 10 10 10 10 10 10 10 10 10]
 [20 20 20 20 20 20 20 20 20 20]
 [30 30 30 30 30 30 30 30 30 30]
 [40 40 40 40 40 40 40 40 40 40]
 [50 50 50 50 50 50 50 50 50 50]
 [60 60 60 60 60 60 60 60 60 60]
 [70 70 70 70 70 70 70 70 70 70]
 [80 80 80 80 80 80 80 80 80 80]
 [90 90 90 90 90 90 90 90 90 90]]


ValueError: all the input array dimensions except for the concatenation axis must match exactly, but along dimension 0, the array at index 0 has size 1 and the array at index 1 has size 100

<Figure size 800x600 with 1 Axes>